name: Build Template (SCL) PDF
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install pandoc with texlive
      run: |
        sudo apt install -y texlive texlive-xetex latexmk wget
        mkdir -p /tmp/pandoc
        cd /tmp/pandoc
        wget -q "https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb"
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb
        rm -rf *.deb
    - name: Install fonts
      run: |
        mkdir adobefont
        cd adobefont
        wget -q -O source-code-pro.zip https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
        wget -q -O source-han-serif.zip https://github.com/adobe-fonts/source-han-serif/archive/1.001R.zip
        wget -q -O source-han-sans.zip https://github.com/adobe-fonts/source-han-sans/archive/2.001R.zip
        unzip -q source-code-pro.zip -d source-code-pro
        unzip -q source-han-serif.zip -d source-han-serif
        unzip -q source-han-sans.zip -d source-han-sans
        rm -rf source-code-pro.zip source-han-serif.zip source-han-sans.zip
        mkdir -p ~/.fonts
        cp -v source-code-pro/*/OTF/*.otf ~/.fonts/
        cp -v source-han-serif/*/SubsetOTF/*/*.otf ~/.fonts/
        cp -v source-han-sans/*/SubsetOTF/*/*.otf ~/.fonts/
        fc-cache -f
    - name: Generate PDF
      run: |
        mkdir -p ~/.pandoc/templates
        cd 算法竞赛/模板
        cp pandoc/algo.latex ~/.pandoc/templates/
        sh pandoc/gen.sh
    - name: Update Tag
      shell: bash
      run: |
        git tag --force continuous-build ${GITHUB_SHA}
        git push --force --tags
    - name: Update Continuous Build Release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: 算法竞赛/模板/template.pdf
        release: Continuous Build
        tag: continuous-build