name: Deploy to Tencent CloudBase
on: page_build
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Deploy static to Tencent CloudBase
        shell: bash
        run: |
          sudo npm i -g @cloudbase/cli
          tcb login --apiKeyId ${{ secrets.SECRET_ID }} --apiKey ${{ secrets.SECRET_KEY }}
          sudo rm -rf .git .github
          tcb hosting deploy . -e ${{ secrets.ENV_ID }} -r ap-guangzhou